---
resources:
- name: resource-web-app
  type: git
  source:
    uri: https://github.com/mmcvay-pivotal/simple-go-web-app.git 

- name: resource-deploy-web-app
  type: cf
  source:
    api:  https://api.local2.pcfdev.io 
    username: admin 
    password: admin 
    organization: pcfdev-org
    space: pcfdev-space
    skip_cert_check: true

jobs:
- name: job-deploy-app
  serial: true
  plan:
  - {get: resource-web-app, trigger: true}
  - put: resource-deploy-web-app
    params:
      manifest: resource-web-app/manifest.yml
      path: resource-web-app
